source 'https://github.com/CocoaPods/Specs.git'

target 'VWBugReporter', :exclusive => true do
  pod "VWBugReporter", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "VWBugReporter", :path => "../"

  
end
